eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name:  trend-trading-backtest-service
  zipkin:
    base-url: http://localhost:9411

feign:
  hystrix:
    enabled: ${backtest.remote.index-data.feign.hystrix-enabled:false}

backtest:
  remote:
    index-data:
      mode: feign
      feign:
        hystrix-enabled: false
      fallback:
        enabled: true
      resilience4j:
        enabled: false
        failure-rate-threshold: 50
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state-ms: 10000
      http:
        base-url: http://localhost:8021

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
