spring:
  profiles: nacos
  application:
    name: index-codes-service
  zipkin:
    base-url: http://localhost:9411
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

eureka:
  client:
    enabled: false

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
