apiVersion: 1

datasources:
  - name: Trend Prometheus
    uid: trend-prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    isDefault: true
    editable: true
