spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:nacos}
  application:
    name: trend-trading-backtest-view
  zipkin:
    base-url: http://localhost:9411

trend:
  web:
    entry-url: ${TREND_WEB_ENTRY_URL:http://127.0.0.1:8032/trend-web/}
    dist-location: ${TREND_WEB_DIST_LOCATION:trend-web/dist/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
