global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: trend-trading-backtest-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8051
        labels:
          application: trend-trading-backtest-service

  - job_name: gateway-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8032
        labels:
          application: gateway-service

  - job_name: index-data-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8021
        labels:
          application: index-data-service

  - job_name: index-codes-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8011
        labels:
          application: index-codes-service

  - job_name: index-gather-store-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8001
        labels:
          application: index-gather-store-service
