spring:
  profiles:
    default: local
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: trend-web
          uri: ${trend.gateway.view-uri:lb://trend-trading-backtest-view}
          predicates:
            - Path=/trend-web/**
        - id: api-market
          uri: ${trend.gateway.market-uri:lb://market-data-service}
          predicates:
            - Path=/api-market/**
          filters:
            - StripPrefix=1
        - id: api-backtest
          uri: ${trend.gateway.backtest-uri:lb://trend-trading-backtest-service}
          predicates:
            - Path=/api-backtest/**
          filters:
            - StripPrefix=1
        - id: api-view
          uri: ${trend.gateway.view-uri:lb://trend-trading-backtest-view}
          predicates:
            - Path=/api-view/**
          filters:
            - StripPrefix=1

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
