spring:
  config:
    activate:
      on-profile: nacos
    import: optional:nacos:gateway-service-dev.yaml
  application:
    name: gateway-service
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848

eureka:
  client:
    enabled: false
