spring:
  application:
    name: trend-trading-backtest-service

  zipkin:
    base-url: http://localhost:9411

server:
  port: 8051

backtest:
  remote:
    index-data:
      mode: feign
      fallback:
        enabled: true
      resilience4j:
        enabled: false
        failure-rate-threshold: 50
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state-ms: 10000
      http:
        base-url: http://localhost:8021

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    enabled: false
